### ISSUE TITLE
Flag to prepend rather than replace GOPATH

### ISSUE THREAD

**Issue by jaschaephraim** [pote/gvp#18]
When I use gvp, I can build my package with vendored dependencies but I can't *install* it because the package itself is no longer in my GOPATH.

If gvp provided an option to prepend my .godeps dir to the path rather than replace it completely, installation isn't a problem.

Thanks for the good work!

**Comment by siddharthist** [comment]
This is the [current behavior](https://github.com/pote/gvp/blob/master/bin/gvp#L44). This issue can be closed.

**Comment by pote** [comment]
Yes it is, thanks for your help @siddharthist !
