### ISSUE TITLE
Prefix shell prompt with gvp marker

### ISSUE THREAD

**Issue by vgarvardt** [pote/gvp#19]
Hello.

gvp is some sort of analogue of virtualenv from python world. When virtualenv is activated it adds prefix to shell prompt, so you always know that you are in, e.g.

```bash
vgarvardt:project vgarvardt$ source .env/bin/activate
(.env)vgarvardt:project vgarvardt$ deactivate
vgarvardt:project vgarvardt$
```

It would be very good if gvp had the same behaviour:

```bash
vgarvardt:project vgarvardt$ source gvp in
(.godeps)vgarvardt:project vgarvardt$ source gvp out
vgarvardt:project vgarvardt$
```

virtualenv allows to create virtualenv in any dir, and set prefix to env dir name, gvp uses same name, so same prefix would be nice in any case.

**Comment by siddharthist** [comment]
This is actually quite easy to do, I might submit a pull request if the zsh issue is fixed before this. All you have to do is export the PS1 environment variable, which then becomes your prompt. Take a look at [how virtualenv does it](https://github.com/pypa/virtualenv/blob/7a8239fc6abaf0ae531b78c24a654372b2fb9fcc/virtualenv_embedded/activate.sh#L57-71).

**Comment by siddharthist** [comment]
I am currently [working on this](https://github.com/siddharthist/prompt-manipulation), I expect to be done in a few days.
