### ISSUE TITLE
gvp as a bash function

### ISSUE THREAD

**Issue by tummychow** [pote/gvp#20]
The `gvp in` and `gvp out` commands have to be sourced, which makes sense but is kinda cumbersome. Could gvp be factored into a bash function instead to remove the need for `source`?

I think this is how some environment managers, like chruby, are designed. The manager is a single [script](https://github.com/postmodern/chruby/blob/master/share/chruby/chruby.sh) that gets sourced in your bashrc. Then that script adds a function to your environment that does all the actual env modification.

My bash-fu is not good enough to contribute this myself, sorry!

**Comment by siddharthist** [comment]
Working on this now.
