### ISSUE TITLE
Bring back 'gvp in <command>'

### ISSUE THREAD

**Issue by blalor** [pote/gvp#23]
Re #21: please bring back `gvp in <command>`; it was core to my build process.  For example, here's how I install the dependencies for my project without having to `source gvp` outside of make: https://github.com/bluestatedigital/riemann-consul-receiver/blob/8a98bd861152be221dc0ebbcaadf53ae33fb170d/Makefile#L31-L32

The way this Makefile's written, the only thing the build host needs is `go` and `make`; everything else is installed as part of the build process.

**Comment by siddharthist** [comment]
@pote Prettu sure that this is how [current master works](https://github.com/pote/gvp/blob/d9940ec12fcf86652324c6d1a7b31e9ab1e5fe14/bin/gvp#L50-52). This issue can probably be closed.
