### ISSUE TITLE
Issue a new release

### ISSUE THREAD

**Issue by siddharthist** [pote/gvp#34]
I think it's about time for a new release, considering the amount of issues closed recently (especially PR #31). 

v0.3.0 would probably be appropriate.

**Comment by pote** [comment]
+1! It's also important to push that release to Homebrew, I believe the version there is *really* outdated.

**Comment by siddharthist** [comment]
@pote I don't know how to do that, would you be willing to help out?

**Comment by pote** [comment]
Absolutely! 

Homebrew uses files called "formulae" that is basically a script which can install and test a given thing. Here's the one for gvp https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gvp.rb

The only required changes are to change the `url` and `sha1` fields to the latest version, verify that the formula works [by testing it](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#test-the-formula) and finally send a Pull Request to Homebrew.

Anyways, I am willing to help out if you don't want or don't have time to go throgh that part. :)

**Comment by siddharthist** [comment]
@pote My only worry is that I don't have access to an OSX computer. Can I effectively test homebrew on Linux?

**Comment by pote** [comment]
I don't think so. :(

Don't worry about it, once the release is made I'll take care of the homebrew update. :)

**Comment by siddharthist** [comment]
Release ready and done after 8bcab74540a9496480190594c605fd46c7d6d76b
