### ISSUE TITLE
`source gvp` fails if GOPATH is unset

### ISSUE THREAD

**Issue by 0xmohit** [pote/gvp#39]
If `GOPATH` is unset to begin with, `source gvp` would fail if using Go 1.5 (beta or rc versions).

To elaborate, the following would work when issuing a `go` command (`go build`, for example):

```
GOPATH=/home/user/.godeps:/home/user
```

while the following won't:

```
GOPATH=/home/user/.godeps:/home/user:
```

It appears that the reason is that `go` now rejects relative path entries in the `GOPATH` variable.  Please refer to https://github.com/golang/go/commit/239ec73e66b4c4706b2261082857d5afa5c53da9 for details.

**Comment by siddharthist** [comment]
Fixed in d1331b123ce1d1171fe086de8b77da4c15bfe3d5
